# ================================================================
# SSM PARAMETER STORE (Secrets Management)
# ================================================================
# Only stores SENSITIVE credentials
# Non-sensitive config (email settings, OAuth URIs, etc.) are direct values in prod.tfvars
#
# Update these values after deployment:
# aws ssm put-parameter --name "/careconnect/prod/db/jdbc_uri" \
#   --value "jdbc:postgresql://YOUR-RDS-ENDPOINT:5432/careconnect" \
#   --type "SecureString" --overwrite

module "ssm_parameters" {
  source = "./modules/ssm"

  # SSM parameters for SENSITIVE credentials only
  parameters = {
    # Database credentials (managed by RDS)
    "/careconnect/prod/db/jdbc_uri" = {
      value       = "jdbc:postgresql://careconnect-db.cide04eqicml.us-east-1.rds.amazonaws.com/careconnect"
      description = "Database JDBC URI"
    }
    "/careconnect/prod/db/username" = {
      value       = "careconnect_admin"
      description = "Database username"
    }
    "/careconnect/prod/db/password" = {
      value       = "careconnect2025#"
      description = "Database password (auto-generated by RDS)"
    }
    
    # Google OAuth (sensitive credentials only)
    "/careconnect/prod/google/client_id" = {
      value       = "PLACEHOLDER-UPDATE-WITH-GOOGLE-CLIENT-ID"
      description = "Google OAuth client ID"
    }
    "/careconnect/prod/google/client_secret" = {
      value       = "PLACEHOLDER-UPDATE-WITH-GOOGLE-CLIENT-SECRET"
      description = "Google OAuth client secret"
    }
    
    # Fitbit (sensitive credentials only)
    "/careconnect/prod/fitbit/client_id" = {
      value       = "PLACEHOLDER-UPDATE-WITH-FITBIT-CLIENT-ID"
      description = "Fitbit client ID"
    }
    "/careconnect/prod/fitbit/client_secret" = {
      value       = "PLACEHOLDER-UPDATE-WITH-FITBIT-CLIENT-SECRET"
      description = "Fitbit client secret"
    }
    
    # Optional: Stripe (if using)
    "/careconnect/prod/stripe/secret_key" = {
      value       = "PLACEHOLDER-OPTIONAL"
      description = "Stripe secret key (optional)"
    }
    
    # Optional: OpenAI (if using)
    "/careconnect/prod/openai/api_key" = {
      value       = "PLACEHOLDER-OPTIONAL"
      description = "OpenAI API key (optional)"
    }
  }

  tags = local.default_tags
}
