version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=careconnect
    ports: ["3306:3306"]
  mailhog:
    image: mailhog/mailhog:latest
    ports: ["1025:1025","8025:8025"]
