AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FocusEd AI C++ Code Execution Lambda Function

Resources:
  CppExecutor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: focusedai-cpp-executor
      PackageType: Image
      Timeout: 120
      MemorySize: 1024
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: ["*"]
          AllowMethods: ["POST"]
          AllowHeaders: ["*"]
    Metadata:
      DockerTag: cpp-v1
      DockerContext: ./cpp
      Dockerfile: Dockerfile

Outputs:
  CppExecutorUrl:
    Description: "C++ Executor Function URL"
    Value: !GetAtt CppExecutorUrl.FunctionUrl
