import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../config/env_constant.dart';

/// Service for generating EDI (Electronic Data Interchange) files
/// EDI is commonly used in healthcare for billing and claims processing
class EdiService {
  static String get _baseUrl => getBackendBaseUrl();
  
  /// Generate EDI 837 (Healthcare Claim) file for a completed visit
  Future<EdiGenerationResult> generateEdi837({
    required int visitId,
    required int patientId,
    required int caregiverId,
    required DateTime visitDate,
    required Duration visitDuration,
    required List<String> servicesProvided,
    required String location,
    String? notes,
  }) async {
    try {
      final requestData = {
        'visitId': visitId,
        'patientId': patientId,
        'caregiverId': caregiverId,
        'visitDate': visitDate.toIso8601String(),
        'visitDuration': visitDuration.inMinutes,
        'servicesProvided': servicesProvided,
        'location': location,
        'notes': notes,
        'ediType': '837', // Healthcare Claim
      };

      final response = await http.post(
        Uri.parse('$_baseUrl/api/edi/generate-837'),
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/edi-x12',
        },
        body: jsonEncode(requestData),
      );

      if (response.statusCode == 200) {
        return EdiGenerationResult(
          success: true,
          ediContent: response.body,
          fileName: 'visit_${visitId}_edi_837.txt',
          message: 'EDI 837 file generated successfully',
        );
      } else {
        return EdiGenerationResult(
          success: false,
          error: 'Failed to generate EDI file: ${response.statusCode}',
        );
      }
    } catch (e) {
      return EdiGenerationResult(
        success: false,
        error: 'Error generating EDI file: $e',
      );
    }
  }

  /// Generate EDI 835 (Healthcare Claim Payment/Advice) file
  Future<EdiGenerationResult> generateEdi835({
    required int visitId,
    required int patientId,
    required double paymentAmount,
    required String paymentMethod,
    required DateTime paymentDate,
  }) async {
    try {
      final requestData = {
        'visitId': visitId,
        'patientId': patientId,
        'paymentAmount': paymentAmount,
        'paymentMethod': paymentMethod,
        'paymentDate': paymentDate.toIso8601String(),
        'ediType': '835', // Healthcare Claim Payment/Advice
      };

      final response = await http.post(
        Uri.parse('$_baseUrl/api/edi/generate-835'),
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/edi-x12',
        },
        body: jsonEncode(requestData),
      );

      if (response.statusCode == 200) {
        return EdiGenerationResult(
          success: true,
          ediContent: response.body,
          fileName: 'payment_${visitId}_edi_835.txt',
          message: 'EDI 835 file generated successfully',
        );
      } else {
        return EdiGenerationResult(
          success: false,
          error: 'Failed to generate EDI file: ${response.statusCode}',
        );
      }
    } catch (e) {
      return EdiGenerationResult(
        success: false,
        error: 'Error generating EDI file: $e',
      );
    }
  }

  /// Generate a mock EDI 837 file for demonstration purposes
  /// In a real implementation, this would be generated by the backend
  Future<EdiGenerationResult> generateMockEdi837({
    required int visitId,
    required int patientId,
    required int caregiverId,
    required DateTime visitDate,
    required Duration visitDuration,
    required List<String> servicesProvided,
    required String location,
    String? notes,
  }) async {
    try {
      // Simulate network delay
      await Future.delayed(const Duration(seconds: 2));

      // Generate mock EDI 837 content
      final ediContent = _generateMockEdi837Content(
        visitId: visitId,
        patientId: patientId,
        caregiverId: caregiverId,
        visitDate: visitDate,
        visitDuration: visitDuration,
        servicesProvided: servicesProvided,
        location: location,
        notes: notes,
      );

      return EdiGenerationResult(
        success: true,
        ediContent: ediContent,
        fileName: 'visit_${visitId}_edi_837_${DateTime.now().millisecondsSinceEpoch}.txt',
        message: 'Mock EDI 837 file generated successfully',
      );
    } catch (e) {
      return EdiGenerationResult(
        success: false,
        error: 'Error generating mock EDI file: $e',
      );
    }
  }

  /// Generate mock EDI 837 content
  String _generateMockEdi837Content({
    required int visitId,
    required int patientId,
    required int caregiverId,
    required DateTime visitDate,
    required Duration visitDuration,
    required List<String> servicesProvided,
    required String location,
    String? notes,
  }) {
    final buffer = StringBuffer();
    
    // EDI 837 Header
    buffer.writeln('ISA*00*          *00*          *ZZ*CARECONNECT      *ZZ*PAYER           *${_formatEdiDate(visitDate)}*${_formatEdiTime(visitDate)}*^*00501*000000001*0*P*>');
    buffer.writeln('GS*HC*CARECONNECT*PAYER*${_formatEdiDate(visitDate)}*${_formatEdiTime(visitDate)}*1*X*005010X222A1');
    buffer.writeln('ST*837*0001*005010X222A1');
    buffer.writeln('BHT*0019*00*1*${_formatEdiDate(visitDate)}*${_formatEdiTime(visitDate)}*CH');
    
    // Submitter Information
    buffer.writeln('NM1*41*2*CARECONNECT*****46*CARECONNECT001');
    buffer.writeln('PER*IC*CONTACT PERSON*TE*555-123-4567');
    
    // Receiver Information
    buffer.writeln('NM1*40*2*PAYER NAME*****46*PAYER001');
    
    // Billing Provider
    buffer.writeln('NM1*85*2*CARECONNECT*****XX*1234567890');
    buffer.writeln('N3*123 MAIN ST');
    buffer.writeln('N4*ANYTOWN*NY*12345');
    
    // Patient Information
    buffer.writeln('NM1*QC*1*DOE*JOHN****MI*PATIENT$patientId');
    buffer.writeln('N3*456 PATIENT ST');
    buffer.writeln('N4*PATIENT CITY*NY*54321');
    buffer.writeln('DMG*D8*19800101*M');
    
    // Insurance Information
    buffer.writeln('NM1*IL*1*INSURANCE*COMPANY*****PI*INS001');
    
    // Claim Information
    buffer.writeln('CLM*$visitId*${visitDuration.inMinutes}***11:B:1*Y*A*Y*I');
    
    // Service Lines
    for (int i = 0; i < servicesProvided.length; i++) {
      final service = servicesProvided[i];
      buffer.writeln('LX*${i + 1}');
      buffer.writeln('SV2*0300*${visitDuration.inMinutes}*UN*1');
      buffer.writeln('DTP*472*D8*${_formatEdiDate(visitDate)}');
    }
    
    // Location Information
    buffer.writeln('N3*$location');
    
    // Notes
    if (notes != null && notes.isNotEmpty) {
      buffer.writeln('NTE*ADD*1*$notes');
    }
    
    // Footer
    buffer.writeln('SE*${_countLines(buffer.toString())}*0001');
    buffer.writeln('GE*1*1');
    buffer.writeln('IEA*1*000000001');
    
    return buffer.toString();
  }

  String _formatEdiDate(DateTime date) {
    return '${date.year}${date.month.toString().padLeft(2, '0')}${date.day.toString().padLeft(2, '0')}';
  }

  String _formatEdiTime(DateTime date) {
    return '${date.hour.toString().padLeft(2, '0')}${date.minute.toString().padLeft(2, '0')}';
  }

  int _countLines(String content) {
    return content.split('\n').length;
  }
}

/// Result of EDI generation operation
class EdiGenerationResult {
  final bool success;
  final String? ediContent;
  final String? fileName;
  final String? message;
  final String? error;

  EdiGenerationResult({
    required this.success,
    this.ediContent,
    this.fileName,
    this.message,
    this.error,
  });
}

/// EDI file types supported
enum EdiFileType {
  edi837('837', 'Healthcare Claim'),
  edi835('835', 'Healthcare Claim Payment/Advice'),
  edi270('270', 'Healthcare Eligibility Request'),
  edi271('271', 'Healthcare Eligibility Response');

  const EdiFileType(this.code, this.description);
  
  final String code;
  final String description;
}
