package com.focusedai.caila.utils;

import com.focusedai.caila.models.CailaRequest;
import org.springframework.stereotype.Component;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Component
public class ContentFormatter {
    
    public String formatChatLog(CailaRequest request, String response) {
        StringBuilder content = new StringBuilder();
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        
        content.append("CAILA AI Assistant Chat Log\n");
        content.append("=".repeat(60)).append("\n");
        content.append("Student: ").append(request.getStudentId()).append("\n");
        content.append("Course ID: ").append(request.getCourseId()).append("\n");
        content.append("Created: ").append(timestamp).append("\n");
        content.append("=".repeat(60)).append("\n\n");
        
        content.append("[").append(timestamp).append("]\n");
        content.append("STUDENT: ").append(request.getPrompt()).append("\n\n");
        content.append("CAILA: ").append(response).append("\n\n");
        content.append("-".repeat(50)).append("\n\n");
        
        return content.toString();
    }
    
    public String formatForMoodle(String content, String materialType) {
        StringBuilder html = new StringBuilder();
        
        html.append("<div style='border: 3px solid #ff9800; padding: 15px; margin-bottom: 20px; background-color: #fff3e0;'>");
        html.append("<h2 style='color: #ff9800; margin: 0;'>🎓 CAILA AI Generated Material</h2>");
        html.append("<p style='margin: 8px 0 0 0;'>");
        html.append("<strong>Material Type:</strong> ").append(materialType != null ? materialType.toUpperCase() : "CONTENT").append("<br>");
        html.append("<strong>Generated:</strong> ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMM dd, yyyy 'at' HH:mm"))).append("<br>");
        html.append("</p>");
        html.append("</div>");
        
        html.append("<div style='border: 1px solid #ddd; padding: 15px; background-color: white;'>");
        html.append("<h3>Content:</h3>");
        html.append("<div style='background-color: #f5f5f5; padding: 10px; border-radius: 4px;'>");
        
        if (content != null && !content.trim().isEmpty()) {
            String htmlContent = content.replaceAll("\n", "<br>")
                                        .replaceAll("\\*\\*(.*?)\\*\\*", "<strong>$1</strong>")
                                        .replaceAll("\\*(.*?)\\*", "<em>$1</em>");
            html.append(htmlContent);
        } else {
            html.append("<p>No content provided.</p>");
        }
        
        html.append("</div>");
        html.append("</div>");
        
        html.append("<div style='margin-top: 20px; padding: 10px; background-color: #f0f0f0; border-radius: 4px; font-size: 12px; color: #666;'>");
        html.append("<p style='margin: 0;'><em>Generated by CAILA AI Assistant</em></p>");
        html.append("</div>");
        
        return html.toString();
    }
    
    public String formatForGoogle(String content, String materialType) {
        StringBuilder formatted = new StringBuilder();
        
        formatted.append("CAILA AI Generated ").append(materialType.toUpperCase()).append("\n");
        formatted.append("=".repeat(50)).append("\n\n");
        formatted.append("Generated: ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMM dd, yyyy 'at' HH:mm"))).append("\n\n");
        formatted.append(content).append("\n\n");
        formatted.append("-".repeat(30)).append("\n");
        formatted.append("Generated by CAILA AI Assistant");
        
        return formatted.toString();
    }
}